### ISSUE TITLE
Investigates rollbacks to a previous version

### ISSUE THREAD

**Issue by hannehue** [hannehue/Trackmania#22]

**Comment by IsabellaNorup** [comment]
Possibly just by making documentation on how we'd do it by rerunning older workflow-runs.

**Comment by IsabellaNorup** [comment]
# How to rollback!

1. Go to https://github.com/hannehue/Trackmania/actions/workflows/Main.yml
2. Select the run you want to revert back to. Look at the commit ID's
![image](https://github.com/user-attachments/assets/f49944a9-2d0a-475c-ba22-bd5f67b5de52)
3. Select the environment stage and click the "rerun this job" button.
![image](https://github.com/user-attachments/assets/38a713e1-915c-457f-a355-ccfd868ae856)

Success1
